---
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8

workspace: &workspace '/tmp/app'
node-image: &node-image 'cimg/node:18.14.1'

jobs:
  dependencies:
    docker:
      - image: *node-image
    working_directory: *workspace
    steps:
      - checkout
      - restore_cache:
          name: Restore cached node_modules
          keys:
            - v1-node_modules-{{ checksum "package-lock.json" }}
            - v1-node_modules-
      - run: npm ci
      - save_cache:
          key: v1-node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: *workspace
          paths:
            - .

  linting:
    docker:
      - image: *node-image
    working_directory: *workspace
    steps:
      - attach_workspace:
          at: *workspace
      - run: npm run lint:prettier
      - run: npm run lint:eslint
  test:
    docker:
      - image: *node-image
    working_directory: *workspace
    steps:
      - attach_workspace:
          at: *workspace
      - run: npm run test

workflows:
  version: 2
  docker-build:
    jobs:
      - dependencies:
          context:
            - VOODOO_NPM_RO

      - aws-ecr/build-and-push-image:
          executor:
            name: aws-ecr/default
            use-docker-layer-caching: true
          create-repo: false
          no-output-timeout: 20m
          repo: vgp/"$CIRCLE_PROJECT_REPONAME"
          skip-when-tags-exist: true
          tag: << pipeline.git.revision >>
          extra-build-args: '--build-arg NPM_TOKEN=${NPM_TOKEN}'
          context:
            - VOODOO_INFRA_TOOLS
            - VOODOO_NPM_RO
          requires:
            - linting
            - test
      - linting:
          requires:
            - dependencies

      - test:
          requires:
            - dependencies
