version: '3.8'
services:
  db:
    image: postgres:15.6-alpine
    ports:
      - '5432:5432'
    env_file:
      - ../.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
      - mikro-orm-issue-db:/var/lib/postgresql/data11
volumes:
  mikro-orm-issue-db:
